// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5O8FnhURlZUnije7AwCtkjfqrPrY9C0',
    appId: '1:890229837369:web:850a04f81398135125c7e8',
    messagingSenderId: '890229837369',
    projectId: 'training-147f7',
    authDomain: 'training-147f7.firebaseapp.com',
    storageBucket: 'training-147f7.appspot.com',
    measurementId: 'G-HWTDMY57ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEn-XIEcoLD31ZX2_22jgys32LoKdLi9Q',
    appId: '1:890229837369:android:e139a594bbb80d5c25c7e8',
    messagingSenderId: '890229837369',
    projectId: 'training-147f7',
    storageBucket: 'training-147f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuAo6lAsO2PVmfV8hlQNCBghEj9l3pHN0',
    appId: '1:890229837369:ios:9b5b931997a6c0a425c7e8',
    messagingSenderId: '890229837369',
    projectId: 'training-147f7',
    storageBucket: 'training-147f7.appspot.com',
    iosClientId: '890229837369-r8p551hs8s382nsnbsgq3e56k3u5vk71.apps.googleusercontent.com',
    iosBundleId: 'com.evaly.Evaly.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuAo6lAsO2PVmfV8hlQNCBghEj9l3pHN0',
    appId: '1:890229837369:ios:b43d7967779bdee125c7e8',
    messagingSenderId: '890229837369',
    projectId: 'training-147f7',
    storageBucket: 'training-147f7.appspot.com',
    iosClientId: '890229837369-ffejbphkc3sov2u55s07cesq9usepdl3.apps.googleusercontent.com',
    iosBundleId: 'com.evaly.Evaly.training.RunnerTests',
  );
}
